class Parser:
    def parseJson(json, option):
        return {
            'sc': lambda json:json['sectionListRenderer']['contents'][0]['itemSectionRenderer']['contents'][0]['playlistVideoListRenderer'],
            'co': lambda json:json['sidebar']['playlistSidebarRenderer']['items'][0]['playlistSidebarPrimaryInfoRenderer']['stats'][0],
            'tr': lambda json:json['contents']['twoColumnWatchNextResults']['secondaryResults']['secondaryResults']['results'],
            'ct': lambda json:json['contents']['twoColumnSearchResultsRenderer']['primaryContents']['sectionListRenderer'],
            'ea': lambda json:json['onResponseReceivedEndpoints'][0]['appendContinuationItemsAction']['continuationItems'],
            'oa': lambda json:json['onResponseReceivedCommands'][0]['appendContinuationItemsAction']['continuationItems'],
            'aa': lambda json:json['onResponseReceivedActions'][0]['appendContinuationItemsAction']['continuationItems'],
            'ci': lambda json:json['contents']['twoColumnSearchResultsRenderer']['primaryContents']['richItemRenderer'],
            'cc': lambda json:json['continuationItemRenderer']['continuationEndpoint']['continuationCommand']['token'],
            'tc': lambda json:json['contents']['twoColumnBrowseResultsRenderer']['tabs'][0]['tabRenderer']['content'],
            'vv': lambda json:json['viewCount']['videoViewCountRenderer']['viewCount']['simpleText'],
            'ap': lambda json:json['searchPyvRenderer']['ads'][0]['promotedVideoRenderer'],
            'mc': lambda json:json['metadata']['channelMetadataRenderer']['channelUrl'],
            'vi': lambda json:json['content']['verticalListRenderer']['items'],
            'ic': lambda json:json[0]['itemSectionRenderer']['contents'],
            'gc': lambda json:json['richGridRenderer']['contents'],
            'rc': lambda json:json['richItemRenderer']['content'],
            'ca': lambda json:json['compactRadioRenderer'],
            'cv': lambda json:json['compactVideoRenderer'],
            'ts': lambda json:json['title']['simpleText'],
            'pr': lambda json:json['playlistRenderer'],
            'rt': lambda json:json['runs'][0]['text'],
            'cr': lambda json:json['channelRenderer'],
            'rr': lambda json:json['radioRenderer'],
            'vr': lambda json:json['videoRenderer'],
            'sr': lambda json:json['shelfRenderer'],
            'pd': lambda json:json['playlistId'],
            'cd': lambda json:json['channelId'],
            'vd': lambda json:json['videoId'],
            'c':  lambda json:json['contents'],
            't':  lambda json:json['title']
        }.get(option)(json)